### ISSUE TITLE
Cannot load an EXR image without a default layer

### ISSUE THREAD

**Issue by MKimiSH** [disneyresearch/jeri#14]
Hi, 

I have some multi-layer EXR images without a default layer (i.e., an image could contain `color`, `normal`, `albedo` layers but no `<default>`). When I try to load one of these images with Jeri, I got an error message: `Error: EXR image not supported`. I wondered for some time why it doesn't support my EXR images but the example ones. Then I realized that my images have no default layer, which confused Jeri as it didn't know which layer to load and thus gave this general error. 

Is my conjecture correct? If so, is there a way to specify the layer to load in Jeri (like `layer: normal`)? 

Thanks a lot!

**Comment by cbreak-black** [comment]
Hi

Jeri is basically only intended to work with images that are generated for it, either single channel images, or images with an 'R', a 'G' and a 'B' channel. If you want to use Jeri, it is best to generate separate images conforming to one of the two supported formats. But if you can not, or want to visualize something else, check out https://github.com/disneyresearch/jeri/blob/19c4cc18ad6a35dc8f872774447294ddf2f7ccf4/src/utils/exr-parser.worker.js#L83-L104, this is the code responsible for decoding.

**Comment by MKimiSH** [comment]
Thanks for the prompt response. I was thinking about similar things, and it is quite easy to split the images as an automatic post-process. I will do it in this way. 
In addition, I heard that loading one layer from a multi-layer EXR will actually require loading of the entire file which can be slow if there are a lot of layers. So I believe the current design serves its purpose well, though it would be nice to have the additional functionality.  

Should I close the issue or leave it as an "enhancement option"?

**Comment by cbreak-black** [comment]
Loading one layer from a multi layer EXR is indeed not cheap, but the API I chose between the C++ side (exr-wrap-em) and jeri's exr-parser-worker is not made for efficiency but ease-of-use, it decodes the same image three times, to read out different channels.

I'll close the ticket for now, but maybe we should revisit the decoding code, since there is potential for improvement. But I'm not sure what the semantic of supporting multiple channels would be exactly.
