### ISSUE TITLE
Canvas size grows exponentially to >33M pixels tall

### ISSUE THREAD

**Issue by mmp** [disneyresearch/jeri#2]
I *think* I'm just doing what the docs tell me to do, but I'm seeing strange behavior.

Repro steps:
1. Check out and build jeri
2. Copy [bug.html.txt](https://github.com/disneyresearch/jeri/files/2346109/bug.html.txt) to the build_web/examples directory (renaming it to bug.html)
3. Start a webserver and open the file.

The image starts zooming automatically as the canvas size grows rapidly, finally stopping when it's around 33M pixels (you can watch its size zoom up in the Chrome element inspector, for example). This happens on both Chrome and Safari on OSX.

The test case shows another issue as well (commented out): if I instead try to render an EXR to a div, then the rest of the contents of the webpage are obliterated.

(Note that I'm not very experienced with modern web/JS stuff, so I imagine this is user error, but I haven't been able to figure it out and am pretty sure I'm following the directions.)

**Comment by tvogels** [comment]
Hi Matt,

Thanks for reporting this problem. Both the 'complete' EXR viewer and the customizable layer-based approach that you have experimented with, rely on the viewer stretching to cover the enclosing DOM element (parent). 

**Full viewer**
To prevent the JERI viewer (commented out) from taking over the whole screen, you can wrap it in a `div` with the desired size:
```
<div style="width: 500px; height: 500px; position: relative;"> <!-- wrapper -->
<div id="my-viewer"></div> 
</div>
```
Note the `position: relative` which is required for CSS to treat the wrapper `div` as a parent for layout calculations.

**Customizable layer-based approach**
When using layers, you also need a wrapping DOM element to determine the sizing. The layers require css rules that make them stretch to full with and height of the parent. (`class="stretch"` takes care of this in the examples.
```
<div style="width:500px; height: 300px; position: relative;">
  <canvas id="image-layer" style="position: absolute; width: 100%; height: 100%;"></canvas>
  <div id="mouse-layer" style="position: absolute; width: 100%; height: 100%;"></div>
</div>
```

**Error in the examples**
To make panning and zooming work, you need to enable the mouse layer with 
```mouseLayer.setEnableMouseEvents(true);```
This was missing in the examples before the latest commit. 


Hope this helps. Let me know if you have further problems. We should add a section to the documentation to detail this behavior. It might also be worth searching for more intuitive default behavior.

**Comment by tvogels** [comment]
Let's keep this open until this is added to the documentation.

**Comment by mmp** [comment]
Hi, Thijs--

Fantastic--that takes care of it for me. It's working perfectly now.

Thanks!
Matt

**Comment by cbreak-black** [comment]
I'm assuming this is resolved then.
