### ISSUE TITLE
RGBA EXRs cause an error to be reported

### ISSUE THREAD

**Issue by mmp** [disneyresearch/jeri#4]
If given a 4-channel EXR, jeri doesn't display the image; the following is reported:

```
Error: Don't know what to do with 4 image channels. ImageLayer.ts:521:14
ImageLayer</ImageLayer.prototype.createTexture
ImageLayer.ts:521:14
<anonymous> self-hosted:986:17 cachedFunction/<
cached-function.ts:11:22
ImageLayer</ImageLayer.prototype.draw
ImageLayer.ts:365:46
ImageLayer</ImageLayer.prototype.checkRender
ImageLayer.ts:304:6
<anonymous> self-hosted:986:17 
```

at minimum it would be nice if they worked (though it's easy enough to work-around by creating an RGB version of the EXR). (Ideally, it'd be nice if alpha was used when rendering the EXR.)

**Comment by cbreak-black** [comment]
Hi

The exr decoder backend should support any number of channels, but the java script side should only extract 1 or 3 channel images: https://github.com/disneyresearch/jeri/blob/b664fa9b740c2962da6aca61506c4722a1d31cb6/src/utils/exr-parser.worker.js#L83-L101

If given an image with more than 1 channels, R, G and B are extracted. I'm unsure how a 4 channel image reached the Image Layer.

**Comment by tvogels** [comment]
I think the problem with parseExr is that even though it parses RGB, it will set nChannels to the original number of channels (which would be 4). This should be overwritten by 3 in that branch. Supporting alpha would be best though.

**Comment by cbreak-black** [comment]
Yes, fixing it to correctly report 3 channels seems like a good choice.

For alpha, we'd need some kind of background to render it on top, in addition to creating an alpha texture, otherwise it'd be a bit pointless. And then there's the question of whether it's premultiplied or not. Not completely trivial :)
