### ISSUE TITLE
Some examples do not function as expected

### ISSUE THREAD

**Issue by danbabcock3d** [disneyresearch/jeri#6]
- Text overlay HUD (zoom in)
- Basic image canvas with zoom and panning

These examples display an image, but don't seem to allow for interaction properly

**Comment by cbreak-black** [comment]
Both work fine for me, using both Firefox 62, Safari 12 and Chrome 69. Can you further describe what doesn't work for you?

**Comment by tvogels** [comment]
Are you on the latest commit? A similarly sounding issue was fixed in a recent commit.

**Comment by cbreak-black** [comment]
Sounds like it was fixed already.
