### ISSUE TITLE
EXRs with crop windows are displayed as black

### ISSUE THREAD

**Issue by mmp** [disneyresearch/jeri#9]
Attached is a zip file with an EXR that has a crop-window specified (the image is roughly 300x300 pixels out of an overall 4000x5600 image. When displayed with jeri, no warnings are issued but the result is black. If I remove the pixelBounds metadata from the EXR, it displays fine.

(It's easy enough to do that to work around it for now, but it'd be nice if this worked.)

[box.zip](https://github.com/disneyresearch/jeri/files/2454459/box.zip)

**Comment by cbreak-black** [comment]
Hi

Please try the new erx-wrap: https://github.com/disneyresearch/openexr-wrap-em/releases/tag/r2, it fixes a problem that prevented it from working with images which had a window not starting at (0,0).

**Comment by mmp** [comment]
Sorry for not checking sooner!

It's still not working for me, even with that update. (Do I need to update anything else?)

I'm now no longer seeing any errors on the console, but the jeri view just says "Downloading...". I can see that the EXR is successfully fetched from the web server, but then nothing seems to happen after that on the jeri side.

**Comment by cbreak-black** [comment]
Weird, for me the fixes seem to work (I am using EXR Wrap r2, as bundled in commit 9c0de05f):
<img width="960" alt="screen shot 2018-10-18 at 08 29 29" src="https://user-images.githubusercontent.com/227017/47135313-fb2de980-d2af-11e8-9757-5e430eb8a4aa.png">

Using exr-wrap.wasm directly via a test script in node also gives sane results.

**Comment by cbreak-black** [comment]
From my tests, EXRs with crop seem to work now, at least the example image I tested with. The EXR API is weird, so it's entirely possible that other problems lurk in the wrapper, but for now I'll close the ticket until I find one I can reproduce :)
